# Generated by Django 5.2.4 on 2025-08-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="item",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
