# Generated by Django 5.2.4 on 2025-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todoitem_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
            ],
        ),
    ]
