# Generated by Django 5.2.4 on 2025-08-06 08:38

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def seed_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Profile = apps.get_model("todo", "Profile")

    Profile(username="example", name="Example User", description="I am an example user.").save()


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_profile"),
    ]

    operations = [
        migrations.RunPython(seed_data)
    ]
