# Generated by Django 5.2.4 on 2025-09-01 10:55

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def seed_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    ToDoList = apps.get_model("todo", "ToDoList")
    ToDoItem = apps.get_model("todo", "ToDoItem")

    todo_list = ToDoList(name="My list")
    todo_list.save()

    ToDoItem(list=todo_list, item="My item", completed=False).save()


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_seed_profile"),
    ]

    operations = [
        migrations.RunPython(seed_data)
    ]
